import { useRouter } from 'expo-router';
import { SymbolView } from 'expo-symbols';
import { StatusBar } from 'expo-status-bar';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const attendees = [['SC','Sarah Chen','Cloud Architect','Microsoft','#7C3AED',false],['JR','James Rodriguez','DevOps Lead','Amazon Web Services','#00A878',true],['PP','Priya Patel','Chief Technology Officer','CloudNative Inc.','#E98200',false],['MW','Michael Wong','Solutions Architect','Google Cloud','#8B55ED',true],['ED','Emily Davis','Platform Engineer','Salesforce','#E51D47',false],['DK','David Kim','Security Engineer','Palo Alto Networks','#E3302D',true],['LT','Lisa Thompson','Enterprise Architect','IBM','#0B98B5',false],['AT','Aiko Tanaka','Cloud Solutions Lead','Fujitsu','#0B98B5',true],['ML','Marcus Lee','Senior SRE','Netflix','#9A36E5',false],['PS','Priya Sharma','Database Cloud Architect','Oracle','#E98200',false],['TH','Tom Henderson','Senior Cloud Consultant','Accenture','#8B55ED',true]];

export default function UserPeopleScreen() {
  const router = useRouter();
  return <View style={styles.screen}><StatusBar style="dark" /><SafeAreaView style={styles.safeArea}>
    <View style={styles.content}><Text style={styles.title}>Attendees</Text><Text style={styles.count}>12 registered professionals</Text><View style={styles.search}><SymbolView name={{ ios: 'magnifyingglass', android: 'search', web: 'search' }} size={15} tintColor="#8894A8" /><TextInput placeholder="Search name, company or role" placeholderTextColor="#97A1B2" style={styles.searchInput} /></View><Text style={styles.results}>12 results</Text>
    <ScrollView contentContainerStyle={styles.card} showsVerticalScrollIndicator={false}>{attendees.map(([initials,name,role,company,color,saved],index) => <View key={String(name)} style={[styles.row,index < attendees.length - 1 && styles.divider]}><View style={[styles.avatar,{backgroundColor:color as string}]}><Text style={styles.avatarText}>{initials}</Text></View><View style={styles.info}><Text style={styles.name}>{name}</Text><Text style={styles.role}>{role}</Text><Text style={styles.company}>{company}</Text></View><Pressable style={styles.linkedin}><Text style={styles.inText}>in</Text></Pressable><Pressable style={styles.save}>{<SymbolView name={{ ios: saved ? 'bookmark.fill' : 'bookmark', android: saved ? 'bookmark' : 'bookmark_border', web: saved ? 'bookmark' : 'bookmark_border' }} size={15} tintColor={saved ? '#7C3AED' : '#8F9AAD'} />}</Pressable></View>)}</ScrollView></View>
    <View style={styles.tabBar}><Pressable onPress={() => router.replace('/dashboard')} style={styles.tab}><SymbolView name={{ios:'house',android:'home',web:'home'}} size={18} tintColor="#64748B"/><Text style={styles.tabText}>Home</Text></Pressable><Pressable onPress={() => router.replace('/agenda')} style={styles.tab}><SymbolView name={{ios:'calendar',android:'calendar_month',web:'calendar_month'}} size={18} tintColor="#64748B"/><Text style={styles.tabText}>Agenda</Text></Pressable><View style={styles.tab}><SymbolView name={{ios:'chart.bar',android:'bar_chart',web:'bar_chart'}} size={18} tintColor="#64748B"/><Text style={styles.tabText}>Charts</Text></View><View style={styles.tabActive}><SymbolView name={{ios:'person.2',android:'group',web:'group'}} size={18} tintColor="#7B3FF0"/><Text style={styles.tabActiveText}>People</Text></View><Pressable onPress={() => router.replace('/saved')} style={styles.tab}><SymbolView name={{ios:'bookmark',android:'bookmark',web:'bookmark'}} size={18} tintColor="#64748B"/><Text style={styles.tabText}>Saved</Text></Pressable><Pressable onPress={() => router.replace('/profile')} style={styles.tab}><SymbolView name={{ios:'person',android:'person',web:'person'}} size={18} tintColor="#64748B"/><Text style={styles.tabText}>Profile</Text></Pressable></View>
  </SafeAreaView></View>;
}

const styles = StyleSheet.create({screen:{flex:1,backgroundColor:'#F7F8FC'},safeArea:{flex:1},content:{flex:1,padding:13,paddingBottom:0},title:{color:'#1E273B',fontSize:25,fontWeight:'800'},count:{color:'#708098',fontSize:11,marginTop:4},search:{height:38,marginTop:14,paddingHorizontal:11,alignItems:'center',flexDirection:'row',gap:7,borderRadius:9,backgroundColor:'#FFF',shadowColor:'#35445F',shadowOpacity:.08,shadowRadius:7,shadowOffset:{width:0,height:2},elevation:2},searchInput:{flex:1,height:'100%',fontSize:11,color:'#29344A'},results:{color:'#6F8099',fontSize:9,fontWeight:'700',marginTop:10,marginBottom:7},card:{overflow:'hidden',borderRadius:13,backgroundColor:'#FFF'},row:{minHeight:59,paddingHorizontal:12,alignItems:'center',flexDirection:'row'},divider:{borderBottomColor:'#E7EAF0',borderBottomWidth:StyleSheet.hairlineWidth},avatar:{height:32,width:32,borderRadius:8,alignItems:'center',justifyContent:'center'},avatarText:{color:'#FFF',fontSize:10,fontWeight:'800'},info:{flex:1,marginLeft:9},name:{color:'#233047',fontSize:11,fontWeight:'800'},role:{color:'#62728B',fontSize:9,marginTop:2},company:{color:'#62728B',fontSize:9,marginTop:1},linkedin:{height:26,width:26,borderRadius:7,alignItems:'center',justifyContent:'center',backgroundColor:'#F0EAFF',marginRight:6},inText:{color:'#7243E4',fontSize:12,fontWeight:'900'},save:{height:26,width:26,borderRadius:7,alignItems:'center',justifyContent:'center',backgroundColor:'#F4F5F8'},tabBar:{height:67,paddingHorizontal:4,flexDirection:'row',alignItems:'center',justifyContent:'space-around',borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:'#E3E8F0',backgroundColor:'#FFF'},tab:{flex:1,alignItems:'center',gap:3},tabActive:{flex:1,alignItems:'center',gap:3},tabText:{color:'#64748B',fontSize:8,fontWeight:'600'},tabActiveText:{color:'#7B3FF0',fontSize:8,fontWeight:'800'}});
