import { SymbolView } from 'expo-symbols';
import { StatusBar } from 'expo-status-bar';
import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useState } from 'react';

const people = [['SA','Super Admin','superadmin@cas.com','Super Admin','#7C3AED'],['CA','Admin User','admin@cloudadoptionsolutions.com','Admin','#121A2E'],['JS','Jane Smith','jane.smith@cas.com','Admin','#7C3AED'],['MD','Mark Davis','mark.davis@cas.com','Admin','#7C3AED'],['SC','Sarah Chen','sarah.chen@demo.com','End User','#7C3AED'],['JR','James Rodriguez','james.rodriguez@demo.com','End User','#00A878'],['PP','Priya Patel','priya.patel@demo.com','End User','#DF7800'],['MW','Michael Wong','michael.wong@demo.com','End User','#8B5CF6'],['ED','Emily Davis','emily.davis@demo.com','End User','#E52F50']];
export default function RoleManagement(){const router=useRouter();const [selected,setSelected]=useState<string|null>(null);return <View style={s.screen}><StatusBar style="dark"/><SafeAreaView style={s.safe}><View style={s.header}><Text style={s.headerText}>Role Management</Text></View><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹  Back</Text></Pressable><Text style={s.title}>Role Management</Text><Text style={s.subtitle}>Assign and change user roles</Text><View style={s.search}><Text>⌕</Text><TextInput placeholder="Search any user" placeholderTextColor="#8A96A9" style={s.input}/></View><View style={s.card}>{people.map(p=><View style={s.row} key={p[1]}><View style={[s.avatar,{backgroundColor:p[4]}]}><Text style={s.avatarText}>{p[0]}</Text></View><View style={s.copy}><Text style={s.name}>{p[1]}</Text><Text style={s.email}>{p[2]}</Text></View><Text style={s.role}>{p[3]}</Text><Pressable onPress={()=>setSelected(p[1])} style={s.edit}><SymbolView name={{ios:'square.and.pencil',android:'edit',web:'edit'}} size={11} tintColor="#7C3AED"/></Pressable></View>)}</View></ScrollView>{selected&&<View style={s.overlay}><View style={s.modal}><Text style={s.modalTitle}>Assign Role</Text><Text style={s.modalSub}>{selected} · superadmin@cas.com</Text>{['End User','Admin','Super Admin'].map(role=><Pressable key={role} style={[s.roleOption,role==='Super Admin'&&s.selectedRole]}><Text style={s.optionIcon}>{role==='Super Admin'?'♔':'○'}</Text><Text style={[s.optionText,role==='Super Admin'&&s.optionSelected]}>{role}</Text>{role==='Super Admin'&&<Text style={s.check}>✓</Text>}</Pressable>)}<Pressable onPress={()=>setSelected(null)} style={s.done}><Text style={s.doneText}>Done</Text></Pressable></View></View>}<View style={s.nav}>{['Home','Events','People','Tools','Users','Profile'].map((x,i)=><View key={x} style={[s.tab,x==='Users'&&s.active]}><SymbolView name={{ios:['house','calendar','person.2','slider.horizontal.3','person.2.fill','person'][i] as never,android:['home','calendar_month','group','tune','group','person'][i] as never,web:['home','calendar_month','group','tune','group','person'][i] as never}} size={15} tintColor="#fff"/><Text style={s.tabText}>{x}</Text></View>)}</View></SafeAreaView></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#F7F8FC'},safe:{flex:1},header:{height:52,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',borderBottomWidth:StyleSheet.hairlineWidth,borderColor:'#E4E8EF'},headerText:{fontSize:13,fontWeight:'800',color:'#1D2639'},content:{padding:12},back:{fontSize:9,fontWeight:'700',color:'#7C3AED'},title:{marginTop:12,fontSize:21,fontWeight:'800',color:'#1D2639'},subtitle:{marginTop:3,fontSize:8,color:'#718098'},search:{height:28,marginTop:9,paddingHorizontal:9,borderRadius:8,flexDirection:'row',gap:6,alignItems:'center',backgroundColor:'#fff'},input:{flex:1,fontSize:9},card:{marginTop:8,borderRadius:10,overflow:'hidden',backgroundColor:'#fff'},row:{minHeight:42,paddingHorizontal:10,alignItems:'center',flexDirection:'row',borderBottomWidth:StyleSheet.hairlineWidth,borderColor:'#E5E9F0'},avatar:{width:23,height:23,borderRadius:6,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:8,fontWeight:'800',color:'#fff'},copy:{flex:1,marginLeft:7},name:{fontSize:8,fontWeight:'800',color:'#253046'},email:{marginTop:2,fontSize:6,color:'#65758C'},role:{paddingHorizontal:5,paddingVertical:2,borderRadius:5,overflow:'hidden',fontSize:6,fontWeight:'800',color:'#7C3AED',backgroundColor:'#F0E9FF'},edit:{width:20,height:20,marginLeft:4,borderRadius:5,backgroundColor:'#F0E9FF',alignItems:'center',justifyContent:'center'},overlay:{...StyleSheet.absoluteFill,backgroundColor:'#0008',justifyContent:'center',padding:8},modal:{borderRadius:12,padding:14,backgroundColor:'#fff'},modalTitle:{fontSize:12,fontWeight:'800',color:'#1D2639'},modalSub:{marginTop:4,marginBottom:10,fontSize:7,color:'#65758C'},roleOption:{height:34,marginBottom:6,paddingHorizontal:10,borderRadius:7,flexDirection:'row',alignItems:'center',backgroundColor:'#F7F8FC',borderWidth:1,borderColor:'#E4E8EF'},selectedRole:{borderColor:'#7C3AED',backgroundColor:'#F5F0FF'},optionIcon:{width:18,fontSize:12,color:'#7C3AED'},optionText:{fontSize:9,color:'#354057'},optionSelected:{color:'#7C3AED',fontWeight:'800'},check:{marginLeft:'auto',color:'#7C3AED'},done:{height:28,borderRadius:6,alignItems:'center',justifyContent:'center',backgroundColor:'#7C3AED'},doneText:{fontSize:9,fontWeight:'800',color:'#fff'},nav:{height:62,backgroundColor:'#000',flexDirection:'row',justifyContent:'space-around',alignItems:'center'},tab:{minWidth:34,paddingVertical:5,alignItems:'center'},active:{paddingHorizontal:10,borderRadius:17,backgroundColor:'#7C3AED'},tabText:{marginTop:2,fontSize:8,color:'#fff'}});

