import { StatusBar } from 'expo-status-bar';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const people = [
  { initials: 'AJ', name: 'Alex Johnson', role: 'Senior Cloud Consultant · Accenture', email: 'alex.j@accenture.com', ticket: 'EB-2025-4821', phone: '+1 (617) 555-0142', submitted: 'Submitted 2 hours ago', color: '#7C3AED' },
  { initials: 'NS', name: 'Nina Shah', role: 'Database Cloud Architect · Oracle', email: 'nina.shah@oracle.com', ticket: 'EB-2025-4822', phone: '+1 (650) 555-0196', submitted: 'Submitted 5 hours ago', color: '#00A878' },
  { initials: 'CT', name: 'Chris Taylor', role: 'Cloud Engineer · Capgemini', email: 'c.taylor@capgemini.com', ticket: 'EB-2025-4823', phone: '+1 (214) 555-0177', submitted: 'Submitted 1 day ago', color: '#E98200' },
];

export default function SuperAdminPeopleScreen() {
  return <View style={styles.screen}><StatusBar style="dark" /><SafeAreaView style={styles.safeArea}><View style={styles.header}><Text style={styles.headerTitle}>Watchlist</Text></View><ScrollView contentContainerStyle={styles.content}><View style={styles.titleRow}><View><Text style={styles.title}>Watchlist</Text><Text style={styles.subtitle}>6 total entries</Text></View><Pressable style={styles.allPeople}><Text style={styles.allPeopleText}>♧ All People</Text></Pressable></View><View style={styles.filters}><Text style={styles.activeFilter}>Pending (3)</Text><Text style={styles.filter}>Approved (2)</Text><Text style={styles.filter}>Rejected (1)</Text></View>{people.map((person) => <View key={person.ticket} style={styles.card}><View style={styles.personHeader}><View style={[styles.avatar, { backgroundColor: person.color }]}><Text style={styles.avatarText}>{person.initials}</Text></View><View style={styles.personInfo}><View style={styles.nameRow}><Text style={styles.name}>{person.name}</Text><Text style={styles.pending}>Pending</Text></View><Text style={styles.role}>{person.role}</Text></View></View><View style={styles.divider} /><Text style={styles.detail}>✉ {person.email}</Text><Text style={styles.detail}># {person.ticket}</Text><Text style={styles.detail}>▣ Cloud Adoption Summit 2025</Text><Text style={styles.detail}>⌕ {person.phone}</Text><Text style={styles.link}>♧ LinkedIn Profile ↗</Text><Text style={styles.submitted}>{person.submitted}</Text><View style={styles.actions}><Pressable style={styles.approve}><Text style={styles.actionText}>♧ Approve</Text></Pressable><Pressable style={styles.reject}><Text style={styles.actionText}>♧ Reject</Text></Pressable></View></View>)}</ScrollView></SafeAreaView></View>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F7F8FC' }, safeArea: { flex: 1 }, header: { height: 52, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF' }, headerTitle: { fontSize: 13, fontWeight: '800' }, content: { padding: 12 }, titleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { fontSize: 23, fontWeight: '800', color: '#1D2639' }, subtitle: { marginTop: 3, fontSize: 10, color: '#718098' }, allPeople: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 16, backgroundColor: '#F0E9FF' }, allPeopleText: { fontSize: 9, fontWeight: '700', color: '#7C3AED' }, filters: { marginVertical: 10, padding: 3, borderRadius: 8, backgroundColor: '#E9EDF3', flexDirection: 'row', justifyContent: 'space-between' }, activeFilter: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6, backgroundColor: '#FFF', fontSize: 8, fontWeight: '800' }, filter: { padding: 6, fontSize: 8, color: '#60718A' }, card: { marginBottom: 10, padding: 12, borderRadius: 13, backgroundColor: '#FFF', elevation: 2 }, personHeader: { flexDirection: 'row', alignItems: 'center' }, avatar: { width: 34, height: 34, borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#FFF', fontSize: 11, fontWeight: '800' }, personInfo: { flex: 1, marginLeft: 9 }, nameRow: { flexDirection: 'row', alignItems: 'center', gap: 7 }, name: { fontSize: 11, fontWeight: '800', color: '#253046' }, pending: { borderRadius: 7, paddingHorizontal: 6, paddingVertical: 3, color: '#FFF', fontSize: 8, fontWeight: '800', backgroundColor: '#E98200', overflow: 'hidden' }, role: { marginTop: 3, fontSize: 8, color: '#65758C' }, divider: { height: StyleSheet.hairlineWidth, marginVertical: 10, backgroundColor: '#E5E9F0' }, detail: { marginBottom: 5, fontSize: 8, color: '#44536A' }, link: { marginBottom: 7, fontSize: 8, color: '#7140E5' }, submitted: { fontSize: 8, color: '#708098' }, actions: { flexDirection: 'row', gap: 8, marginTop: 10 }, approve: { flex: 1, height: 30, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: '#00A878' }, reject: { flex: 1, height: 30, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E92A2A' }, actionText: { color: '#FFF', fontSize: 9, fontWeight: '800' },
});
