import { SymbolView } from 'expo-symbols';
import { StatusBar } from 'expo-status-bar';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import SuperAdminTabBar from '../../components/SuperAdminTabBar';

const users = [['SC', 'Sarah Chen', 'sarah.chen@demo.com', '#7C3AED'], ['JR', 'James Rodriguez', 'james.rodriguez@demo.com', '#00A878'], ['PP', 'Priya Patel', 'priya.patel@demo.com', '#DF7800'], ['MW', 'Michael Wong', 'michael.wong@demo.com', '#8B5CF6'], ['ED', 'Emily Davis', 'emily.davis@demo.com', '#E52F50'], ['DK', 'David Kim', 'david.kim@demo.com', '#E52F28']];
const admins = [['SA', 'Super Admin', 'superadmin@cas.com', '#7C3AED', 'Active'], ['CA', 'Admin User', 'admin@cloudadoptionsolutions.com', '#7C3AED', 'Active'], ['JS', 'Jane Smith', 'jane.smith@cas.com', '#7C3AED', 'Active'], ['MD', 'Mark Davis', 'mark.davis@cas.com', '#7C3AED', 'Disabled']];

export default function UserManagementList({ admin = false }: { admin?: boolean }) {
  const data = admin ? admins : users;
  const title = admin ? 'Admin Users' : 'Users List';
  return <View style={s.screen}><StatusBar style="dark" /><SafeAreaView style={s.safe}><View style={s.header}><Text style={s.headerText}>{title}</Text></View><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><View style={s.titleRow}><View><Text style={s.title}>{title}</Text><Text style={s.count}>{admin ? '4 admins' : '12 end users'}</Text></View>{admin && <Pressable style={s.new}><Text style={s.newText}>+ New Admin</Text></Pressable>}</View>{!admin && <View style={s.search}><SymbolView name={{ ios: 'magnifyingglass', android: 'search', web: 'search' }} size={14} tintColor="#8A96A9" /><TextInput placeholder="Search name or email" placeholderTextColor="#8A96A9" style={s.searchInput} /></View>}<View style={s.list}>{data.map((person) => <View key={person[1]} style={s.row}><View style={[s.avatar, { backgroundColor: person[3] }]}><Text style={s.avatarText}>{person[0]}</Text></View><View style={s.copy}><Text style={s.name}>{person[1]}</Text><Text style={s.email}>{person[2]}</Text><View style={s.badges}><Text style={s.role}>{admin ? 'Admin' : 'End User'}</Text><Text style={[s.status, admin && person[4] === 'Disabled' ? s.disabled : s.active]}>{admin ? person[4] : 'Active'}</Text></View></View><Pressable style={s.iconButton}><SymbolView name={{ ios: 'square.and.pencil', android: 'edit', web: 'edit' }} size={11} tintColor="#7C3AED" /></Pressable><Pressable style={s.delete}><SymbolView name={{ ios: 'trash', android: 'delete', web: 'delete' }} size={11} tintColor="#F05262" /></Pressable></View>)}</View></ScrollView><SuperAdminTabBar activeTab="Users" /></SafeAreaView></View>;
}

const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F7F8FC' }, safe: { flex: 1 }, header: { height: 52, backgroundColor: '#FFF', alignItems: 'center', justifyContent: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderColor: '#E4E8EF' }, headerText: { fontSize: 13, fontWeight: '800', color: '#1D2639' }, content: { padding: 12 }, titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { fontSize: 21, fontWeight: '800', color: '#1D2639' }, count: { marginTop: 3, fontSize: 8, color: '#718098' }, new: { borderRadius: 15, paddingHorizontal: 10, paddingVertical: 7, backgroundColor: '#7C3AED' }, newText: { fontSize: 8, fontWeight: '800', color: '#FFF' }, search: { height: 34, marginTop: 9, paddingHorizontal: 9, borderRadius: 8, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#FFF', elevation: 1 }, searchInput: { flex: 1, fontSize: 10, color: '#354057' }, list: { marginTop: 8, borderRadius: 10, overflow: 'hidden', backgroundColor: '#FFF', elevation: 2 }, row: { minHeight: 54, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderColor: '#E5E9F0' }, avatar: { width: 28, height: 28, borderRadius: 7, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontSize: 9, fontWeight: '800', color: '#FFF' }, copy: { flex: 1, marginLeft: 8 }, name: { fontSize: 9, fontWeight: '800', color: '#253046' }, email: { marginTop: 2, fontSize: 7, color: '#65758C' }, badges: { marginTop: 4, flexDirection: 'row', gap: 4 }, role: { paddingHorizontal: 4, paddingVertical: 1, borderRadius: 3, overflow: 'hidden', fontSize: 6, color: '#65758C', backgroundColor: '#EEF3F9' }, status: { paddingHorizontal: 5, paddingVertical: 1, borderRadius: 4, overflow: 'hidden', fontSize: 6, fontWeight: '800', color: '#FFF' }, active: { backgroundColor: '#00A878' }, disabled: { backgroundColor: '#E52F3F' }, iconButton: { width: 22, height: 22, marginLeft: 3, borderRadius: 5, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F0E9FF' }, delete: { width: 22, height: 22, marginLeft: 3, borderRadius: 5, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF0F1' },
});
