import { SymbolView } from 'expo-symbols';
import { StatusBar } from 'expo-status-bar';
import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useState } from 'react';

const users = [['SC','Sarah Chen','sarah.chen@demo.com','#7C3AED'],['JR','James Rodriguez','james.rodriguez@demo.com','#00A878'],['PP','Priya Patel','priya.patel@demo.com','#DF7800'],['MW','Michael Wong','michael.wong@demo.com','#8B5CF6'],['ED','Emily Davis','emily.davis@demo.com','#E52F50'],['DK','David Kim','david.kim@demo.com','#E52F28']];
const admins = [['SA','Super Admin','superadmin@cas.com','#7C3AED','Active'],['CA','Admin User','admin@cloudadoptionsolutions.com','#7C3AED','Active'],['JS','Jane Smith','jane.smith@cas.com','#7C3AED','Active'],['MD','Mark Davis','mark.davis@cas.com','#7C3AED','Disabled']];
const tabs = [['Home','house','home'],['Events','calendar','calendar_month'],['People','person.2','group'],['Tools','slider.horizontal.3','tune'],['Users','person.2.fill','group'],['Profile','person','person']] as const;

export default function UserManagementList({ admin = false }: { admin?: boolean }) {
 const router=useRouter(), [modal,setModal]=useState<'edit'|'delete'|null>(null), data=admin?admins:users, title=admin?'Admin Users':'Users List';
 return <View style={s.screen}><StatusBar style="dark"/><SafeAreaView style={s.safe}><View style={s.header}><Text style={s.headerText}>{title}</Text></View><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>‹  Back</Text></Pressable><View style={s.titleRow}><View><Text style={s.title}>{title}</Text><Text style={s.count}>{admin?'4 admins':'12 end users'}</Text></View>{admin&&<Pressable style={s.new}><Text style={s.newText}>＋ New Admin</Text></Pressable>}</View>{!admin&&<View style={s.search}><Text>⌕</Text><TextInput placeholder="Search name or email" placeholderTextColor="#8A96A9" style={s.searchInput}/></View>}<View style={s.list}>{data.map((person)=><View key={person[1]} style={s.row}><View style={[s.avatar,{backgroundColor:person[3]}]}><Text style={s.avatarText}>{person[0]}</Text></View><View style={s.copy}><Text style={s.name}>{person[1]}</Text><Text style={s.email}>{person[2]}</Text><View style={s.badges}><Text style={s.role}>{admin?'Admin':'End User'}</Text><Text style={[s.status, admin&&person[4]==='Disabled'?s.disabled:s.active]}>{admin?person[4]:'Active'}</Text></View></View><Pressable onPress={()=>setModal("edit")} style={s.iconButton}><SymbolView name={{ios:'square.and.pencil',android:'edit',web:'edit'}} size={11} tintColor="#7C3AED"/></Pressable><Pressable onPress={()=>setModal("delete")} style={s.delete}><SymbolView name={{ios:'trash',android:'delete',web:'delete'}} size={11} tintColor="#F05262"/></Pressable></View>)}</View></ScrollView><View style={s.nav}>{tabs.map(([label,ios,android])=><Pressable key={label} style={[s.tab,label==='Users'&&s.activeTab]}><SymbolView name={{ios,android,web:android}} size={15} tintColor="#fff"/><Text style={s.tabText}>{label}</Text></Pressable>)}</View></SafeAreaView></View>;
}

const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#F7F8FC'},safe:{flex:1},header:{height:52,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',borderBottomWidth:StyleSheet.hairlineWidth,borderColor:'#E4E8EF'},headerText:{fontSize:13,fontWeight:'800',color:'#1D2639'},content:{padding:12},back:{height:22},backText:{fontSize:9,fontWeight:'700',color:'#7C3AED'},titleRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{fontSize:21,fontWeight:'800',color:'#1D2639'},count:{marginTop:3,fontSize:8,color:'#718098'},new:{borderRadius:15,paddingHorizontal:10,paddingVertical:7,backgroundColor:'#7C3AED'},newText:{fontSize:8,fontWeight:'800',color:'#fff'},search:{height:28,marginTop:9,paddingHorizontal:9,borderRadius:8,flexDirection:'row',alignItems:'center',gap:6,backgroundColor:'#fff',elevation:1},searchInput:{flex:1,fontSize:9,color:'#354057'},list:{marginTop:8,borderRadius:10,overflow:'hidden',backgroundColor:'#fff',elevation:2},row:{minHeight:49,paddingHorizontal:10,flexDirection:'row',alignItems:'center',borderBottomWidth:StyleSheet.hairlineWidth,borderColor:'#E5E9F0'},avatar:{width:23,height:23,borderRadius:6,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:8,fontWeight:'800',color:'#fff'},copy:{flex:1,marginLeft:7},name:{fontSize:8,fontWeight:'800',color:'#253046'},email:{marginTop:2,fontSize:6,color:'#65758C'},badges:{marginTop:3,flexDirection:'row',gap:4},role:{paddingHorizontal:4,paddingVertical:1,borderRadius:3,overflow:'hidden',fontSize:6,color:'#65758C',backgroundColor:'#EEF3F9'},status:{paddingHorizontal:5,paddingVertical:1,borderRadius:4,overflow:'hidden',fontSize:6,fontWeight:'800',color:'#fff'},active:{backgroundColor:'#00A878'},disabled:{backgroundColor:'#E52F3F'},iconButton:{width:20,height:20,marginLeft:3,borderRadius:5,alignItems:'center',justifyContent:'center',backgroundColor:'#F0E9FF'},delete:{width:20,height:20,marginLeft:3,borderRadius:5,alignItems:'center',justifyContent:'center',backgroundColor:'#FFF0F1'},nav:{height:62,backgroundColor:'#000',flexDirection:'row',alignItems:'center',justifyContent:'space-around'},tab:{minWidth:34,alignItems:'center',paddingVertical:5},activeTab:{paddingHorizontal:10,borderRadius:17,backgroundColor:'#7C3AED'},tabText:{marginTop:2,fontSize:8,color:'#fff'}});

