import { SymbolView } from 'expo-symbols';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

export type Person = { initials: string; name: string; role: string; company: string; color: string; saved?: boolean };
export const people: Person[] = [{ initials:'SC',name:'Sarah Chen',role:'Cloud Architect',company:'Microsoft',color:'#7C3AED' },{ initials:'JR',name:'James Rodriguez',role:'DevOps Lead',company:'Amazon Web Services',color:'#00A878',saved:true },{ initials:'PP',name:'Priya Patel',role:'Chief Technology Officer',company:'CloudNative Inc.',color:'#E98200' },{ initials:'MW',name:'Michael Wong',role:'Solutions Architect',company:'Google Cloud',color:'#8B55ED',saved:true },{ initials:'ED',name:'Emily Davis',role:'Platform Engineer',company:'Salesforce',color:'#E51D47' },{ initials:'DK',name:'David Kim',role:'Security Engineer',company:'Palo Alto Networks',color:'#E3302D',saved:true }];

export default function PeopleDirectory({ data = people }: { data?: Person[] }) { const [query,setQuery]=useState(''); const matches=useMemo(()=>{const search=query.trim().toLowerCase();return data.filter(p=>[p.initials,p.name,p.role,p.company].some(v=>v.toLowerCase().includes(search)));},[data,query]); return <View style={s.root}><Text style={s.title}>Attendees</Text><Text style={s.count}>{data.length} registered professionals</Text><View style={s.search}><SymbolView name={{ios:'magnifyingglass',android:'search',web:'search'}} size={15} tintColor="#8894A8"/><TextInput value={query} onChangeText={setQuery} placeholder="Search name, company or role" placeholderTextColor="#97A1B2" style={s.input}/>{query?<Pressable onPress={()=>setQuery('')}><Text style={s.clear}>×</Text></Pressable>:null}</View><Text style={s.results}>{matches.length} results</Text><ScrollView contentContainerStyle={s.card}>{matches.map((p,i)=><View key={p.name} style={[s.row,i<matches.length-1&&s.divider]}><View style={[s.avatar,{backgroundColor:p.color}]}><Text style={s.avatarText}>{p.initials}</Text></View><View style={s.info}><Text style={s.name}>{p.name}</Text><Text style={s.role}>{p.role}</Text><Text style={s.role}>{p.company}</Text></View><View style={s.linkedin}><Text style={s.inText}>in</Text></View>{p.saved?<SymbolView name={{ios:'bookmark.fill',android:'bookmark',web:'bookmark'}} size={15} tintColor="#7C3AED"/>:null}</View>)}{!matches.length?<Text style={s.empty}>No attendees found</Text>:null}</ScrollView></View>; }
const s=StyleSheet.create({root:{flex:1},title:{fontSize:25,fontWeight:'800',color:'#1E273B'},count:{fontSize:11,color:'#708098',marginTop:4},search:{height:38,marginTop:14,paddingHorizontal:11,flexDirection:'row',alignItems:'center',gap:7,borderRadius:9,backgroundColor:'#FFF'},input:{flex:1,height:'100%',fontSize:11,color:'#29344A'},clear:{fontSize:20,color:'#97A1B2'},results:{marginVertical:8,fontSize:9,fontWeight:'700',color:'#6F8099'},card:{overflow:'hidden',borderRadius:13,backgroundColor:'#FFF'},row:{minHeight:59,paddingHorizontal:12,alignItems:'center',flexDirection:'row',gap:9},divider:{borderBottomWidth:StyleSheet.hairlineWidth,borderColor:'#E7EAF0'},avatar:{width:32,height:32,borderRadius:8,alignItems:'center',justifyContent:'center'},avatarText:{color:'#FFF',fontSize:10,fontWeight:'800'},info:{flex:1},name:{fontSize:11,fontWeight:'800',color:'#233047'},role:{fontSize:9,color:'#62728B',marginTop:2},linkedin:{width:26,height:26,borderRadius:7,alignItems:'center',justifyContent:'center',backgroundColor:'#F0EAFF'},inText:{fontSize:12,fontWeight:'900',color:'#7243E4'},empty:{padding:30,textAlign:'center',color:'#718098'}});
